### ISSUE TITLE
Fix nested ordered lists in index

### ISSUE THREAD

**Issue by clhynfield** [mlhynfield/mlhynfield.github.io#1]
From W3C validator:

> Element `ol` not allowed as child of element `ol` in this context.

https://github.com/ButteryPicklz/ButteryPicklz.github.io/blob/7223e0005ab1bbed5f349ac2616dbf15d913563f/index.html#L35

**Comment by clhynfield** [comment]
Hint: Mozilla Developer Network gives an [example of nesting lists](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol#Nesting_lists) that you can copy from.

**Comment by mlhynfield** [comment]
I think I got it

[W3C validator:] <Document checking completed. No errors or warnings to show.>

**Comment by mlhynfield** [comment]
Looks like I need to work on those fancy comment shortcuts

**Comment by clhynfield** [comment]
Nice work!

> Document checking completed. No errors or warnings to show.
