### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by clhynfield** [mlhynfield/mlhynfield.github.io#2]
GitHub makes it easy: https://github.com/ButteryPicklz/ButteryPicklz.github.io/new/master?readme=1

**Comment by mlhynfield** [comment]
I think I created a README

**Comment by clhynfield** [comment]
Heeeey, I said _some_ would contend it's not proper programming. It's definitely code of a sort, though! 

Plus, have no fear – we'll get to some proper programming soon
