### ISSUE TITLE
Make this a hyperlink

### ISSUE THREAD

**Issue by clhynfield** [mlhynfield/mlhynfield.github.io#3]
https://github.com/mlhynfield/mlhynfield.github.io/blob/70827fb7e350580720e83cce2f43bd550c90e093/index.html#L14

It’s _great_ that you’re linking to your LinkedIn profile – gives recruiters, etc. an easy way to see your recommendations, get in touch with you, etc. Can you use the `<a>` element to make this a [hyperlink](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks)?

**Comment by mlhynfield** [comment]
I made the hyperlink, and after 3 commits it actually links to my profile and not a 404 page.
